cek secret hardcoded staging

diff --git a/.github/workflows/test‑secrets.yml b/.github/workflows/test‑secrets.yml
--- a/.github/workflows/test‑secrets.yml
+++ b/.github/workflows/test‑secrets.yml
@@ -30,3 +30,26 @@ jobs:
           fail_if_empty "JWT_SECRET" "$JWT_SECRET"
 
           echo "✨ Semua nilai terdeteksi dengan benar!"
+
+      - name: Hardcoded Secret Test Staging
+        env:
+          APP_SECRET: "appsecret_staging"
+          DATABASE_PASSWORD: "databasepassword_staging"
+          JWT_SECRET: "jwtsecret_staging"
+          
+        run: |
+          fail_if_empty () {
+            if [ -z "$2" ]; then
+              echo "❌ $1 is missing or empty"
+              exit 1
+            else
+              echo "✅ $1 is set to: $2"
+            fi
+          }
+
+          echo "--- Memulai Validasi Hardcoded (Staging) ---"
+          fail_if_empty "APP_SECRET" "$APP_SECRET"
+          fail_if_empty "DATABASE_PASSWORD" "$DATABASE_PASSWORD"
+          fail_if_empty "JWT_SECRET" "$JWT_SECRET"
+
+          echo "✨ Semua nilai Staging terdeteksi dengan benar!"
